### ISSUE TITLE
Documentar Helm Chart (chart.yaml, values.yaml)

### ISSUE THREAD

**Issue by gonzalopages64** [FenicioInfra/helm-chart#1]
Documentar templates(PHP, PHP Performance, Node, Generic, etc), values.yaml y Chart.yaml y sus posibles variables dependiendo del caso

**Comment by javierfiorina** [comment]
@gonzalopages64  
Quedo hecha la doc en el repo: https://github.com/FenicioInfra/php-base/tree/documentacion

Esta en el branch documentacion, habria que validarlo y despues lo pasamos.

**Comment by gonzalopages64** [comment]
Esta ok la doicumentacion en principio Javi, si necesitamos correccion abrimos nueva issue
